### ISSUE TITLE
Posible Error con MariaDB 10.11.4

### ISSUE THREAD

**Issue by Scosrom** [josejuansanchez/iaw-practica-lamp#2]
Buenas, 
Soy una estudiante de ASIR, en primer lugar quería agradecerte la información para realizar la practica.  Mientras la realizaba me ha dado un error que he podido solucionar y que lo mismo consideras interesante revisar.
Un saludo

root@ip-172-26-150-50:/var/www/html/iaw/src# mysql -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 32
Server version: 10.11.4-MariaDB-1~deb12u1 Debian 12

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SET PASSWORD FOR 'lamp_user'@'%' = 'lamp_password';
ERROR 1372 (HY000): Password hash should be a 41-digit hexadecimal number
MariaDB [(none)]> ALTER  USER 'lamp_user'@'%' IDENTIFIED BY 'nueva';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]>

**Comment by josejuansanchez** [comment]
¡Muchas gracias @Scosrom!
